#!/usr/bin/env python3
import os
import re
import sys


def bundle():
    project_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(project_dir, "src")
    dist_file = os.path.join(
        project_dir,
        "../custom_components/snmp_switch_manager/frontend/snmp-switch-manager-card.js",
    )

    files = ["utils.js", "card.js", "editor.js"]

    print("🚀 Starting Python-based ES6 Module Bundler...")

    bundled_content = []

    # Add a top-level banner
    bundled_content.append(
        "/*\n * SNMP Switch Manager Card - Compiled Output\n * Generated by build.py - DO NOT EDIT DIRECTLY\n */\n\n"
    )

    for f_name in files:
        f_path = os.path.join(src_dir, f_name)
        if not os.path.exists(f_path):
            print(f"❌ Error: Required source file '{f_name}' not found at {f_path}")
            sys.exit(1)

        print(f"📦 Processing src/{f_name}...")
        with open(f_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        cleaned_lines = []
        for line in lines:
            # Strip import statements
            if line.strip().startswith("import "):
                continue

            # Strip export keywords
            # Match export patterns cleanly
            line = re.sub(r"^export\s+async\s+function\s+", "async function ", line)
            line = re.sub(r"^export\s+class\s+", "class ", line)
            line = re.sub(r"^export\s+function\s+", "function ", line)
            line = re.sub(r"^export\s+const\s+", "const ", line)
            line = re.sub(r"^export\s+let\s+", "let ", line)
            line = re.sub(r"^export\s+default\s+", "", line)

            cleaned_lines.append(line)

        content = "".join(cleaned_lines)
        bundled_content.append(f"// --- BEGIN src/{f_name} ---\n")
        bundled_content.append(content)
        bundled_content.append(f"\n// --- END src/{f_name} ---\n\n")

    os.makedirs(os.path.dirname(dist_file), exist_ok=True)
    with open(dist_file, "w", encoding="utf-8") as f:
        f.write("".join(bundled_content))

    print(f"🎉 Success! Compiled bundle written to {dist_file}")

    # Run syntax check
    sys.path.append(
        "/home/jamie/.gemini/antigravity-ide/brain/08ac350a-46b2-409c-82be-cd5a6e709532/scratch"
    )
    try:
        import check_syntax

        if check_syntax.check_matching_brackets(dist_file):
            print("✅ Syntax Check: PASSED!")
        else:
            print("❌ Syntax Check: FAILED! Please check matching brackets.")
            sys.exit(1)
    except Exception as e:
        print(f"⚠️ Warning: Could not run syntax check: {e}")


if __name__ == "__main__":
    bundle()
